/* used in Header_FIFO implementation. */

/************************************************************\
 **  Copyright (c) 2011-2021 Anlogic, Inc.
 **  All Right Reserved.
\************************************************************/
/************************************************************\
 ** Log	:	This file is generated by Anlogic IP Generator.
 ** File	:	C:/Users/splas/tinyEtherDeveloper/FPGA_project/L2Switch/al_ip/HEADER_FIFO.v
 ** Date	:	2022 07 25
 ** TD version	:	4.4.433
\************************************************************/

`timescale 1ns / 1ps

module HEADER_FIFO #(
	parameter WIDTH = 128
)(
	rst,
	di, clk, we,
	do, re,
	empty_flag,
	full_flag
);

	input rst;
	input [WIDTH-1:0] di;
	input clk, we;
	input re;

	output [WIDTH-1:0] do;
	output empty_flag;
	output full_flag;

EG_LOGIC_FIFO #(
 	.DATA_WIDTH_W(WIDTH),
	.DATA_WIDTH_R(WIDTH),
	.DATA_DEPTH_W(512),
	.DATA_DEPTH_R(512),
	.ENDIAN("BIG"),
	.RESETMODE("SYNC"),
	.E(0),
	.F(512),
	.ASYNC_RESET_RELEASE("SYNC"))
logic_fifo(
	.rst(rst),
	.di(di),
	.clkw(clk),
	.we(we),
	.csw(3'b111),
	.do(do),
	.clkr(clk),
	.re(re),
	.csr(3'b111),
	.ore(1'b0),
	.empty_flag(empty_flag),
	.aempty_flag(),
	.full_flag(full_flag),
	.afull_flag()

);

endmodule
